### POST request to example server
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Khadija",
  "email": "khadija@gmail.com",
  "adress": "123 main street",
  "dateOfBirth": "2000-09-20",
  "registredDate": "2025-10-22"
}

###